#!/usr/bin/env python2

'''
Created on Mar 20, 2012

The program that updates users that are already in the database so
that they may be up to date.

TODO: handle exceptions (like when we've been making too many twitter requests sleep for 1 hour in the exception handler)

TODO: WRITE MORE DESCRIPTION OF ME?
'''

from addalyse import *
from storageHandler import *
from twitterHelp import *
import time

# TODO: read this from some configuration file in a smart way?
SOLR_SERVER = "http://xantoz.failar.nu:8080/solr/"

# Every UPDATE_N:th update of a profile do a full analysis throwing away the old one
UPDATE_N = 100

def main():
    '''Gets profiles from storageHandler and checks if they need updating, and if so updates those.'''
    
    th = TwitterHelp() 
    sh = StorageHandler(SOLR_SERVER)
    
    limit=UPDATE_N
    
    while True:
        for (username, since_id, update_count, timestamp) in sh.get_user_fields('*', 'id', 'since_id', 'updatecount', 'timestamp'):
            print("updating user " + username + " last updated " + timestamp) # Debug printage
            # TODO: use timestamp to check if already updated updated today (or something like that)
            #       and then choose to not update. (timestamp is automatically generated by solr when adding/updateing a profile)
            if since_id != th.get_latest_tweet_id(username): # check if need updating
                addalyse(SOLR_SERVER,
                         username,
                         since_id,
                         (update_count % UPDATE_N) == 0,
                         update_count + 1) 
            time.sleep(10) # sleep for ten seconds, to not make to many requests to twitter
    
if __name__ == "__main__":
    main()
